/* parser auto-generated by pidl */

#include "includes.h"
#include "bin/default/librpc/gen_ndr/ndr_frstrans.h"

#include "librpc/gen_ndr/ndr_misc.h"

enum ndr_err_code ndr_push_frstrans_Update(struct ndr_push *ndr, int ndr_flags, const struct frstrans_Update *r)
{
	{
		uint32_t _flags_save_STRUCT = ndr->flags;
		ndr_set_flags(&ndr->flags, LIBNDR_PRINT_ARRAY_HEX);
		NDR_PUSH_CHECK_FLAGS(ndr, ndr_flags);
		if (ndr_flags & NDR_SCALARS) {
			uint32_t name_length = strlen_m(r->name) + 1;
			NDR_CHECK(ndr_push_align(ndr, 8));
			NDR_CHECK(ndr_push_uint32(ndr, NDR_SCALARS, r->present));
			NDR_CHECK(ndr_push_uint32(ndr, NDR_SCALARS, r->name_conflict));
			NDR_CHECK(ndr_push_uint32(ndr, NDR_SCALARS, r->attributes));
			NDR_CHECK(ndr_push_NTTIME(ndr, NDR_SCALARS, r->fence));
			NDR_CHECK(ndr_push_NTTIME(ndr, NDR_SCALARS, r->clock));
			NDR_CHECK(ndr_push_NTTIME(ndr, NDR_SCALARS, r->create_time));
			NDR_CHECK(ndr_push_GUID(ndr, NDR_SCALARS, &r->content_set_guid));
			NDR_CHECK(ndr_push_array_uint8(ndr, NDR_SCALARS, r->sha1_hash, 20));
			NDR_CHECK(ndr_push_array_uint8(ndr, NDR_SCALARS, r->rdc_similarity, 16));
			NDR_CHECK(ndr_push_GUID(ndr, NDR_SCALARS, &r->uid_db_guid));
			NDR_CHECK(ndr_push_hyper(ndr, NDR_SCALARS, r->uid_version));
			NDR_CHECK(ndr_push_GUID(ndr, NDR_SCALARS, &r->gsvn_db_guid));
			NDR_CHECK(ndr_push_hyper(ndr, NDR_SCALARS, r->gsvn_version));
			NDR_CHECK(ndr_push_GUID(ndr, NDR_SCALARS, &r->parent_db_guid));
			NDR_CHECK(ndr_push_hyper(ndr, NDR_SCALARS, r->parent_version));
			NDR_CHECK(ndr_push_uint3264(ndr, NDR_SCALARS, 0));
			if (name_length > 261) {
				return ndr_push_error(ndr, NDR_ERR_STRING, "%s", __location__);
			}
			NDR_CHECK(ndr_push_uint3264(ndr, NDR_SCALARS, name_length));
			NDR_CHECK(ndr_push_charset(ndr, NDR_SCALARS, r->name, name_length, sizeof(uint16_t), CH_UTF16));
			NDR_CHECK(ndr_push_uint32(ndr, NDR_SCALARS, r->flags));
			NDR_CHECK(ndr_push_trailer_align(ndr, 8));
		}
		if (ndr_flags & NDR_BUFFERS) {
		}
		ndr->flags = _flags_save_STRUCT;
	}
	return NDR_ERR_SUCCESS;
}

enum ndr_err_code ndr_pull_frstrans_Update(struct ndr_pull *ndr, int ndr_flags, struct frstrans_Update *r)
{
	uint32_t size_sha1_hash_0 = 0;
	uint32_t size_rdc_similarity_0 = 0;
	uint32_t size_name_0 = 0;
	uint32_t length_name_0 = 0;
	{
		uint32_t _flags_save_STRUCT = ndr->flags;
		ndr_set_flags(&ndr->flags, LIBNDR_PRINT_ARRAY_HEX);
		NDR_PULL_CHECK_FLAGS(ndr, ndr_flags);
		if (ndr_flags & NDR_SCALARS) {
			NDR_CHECK(ndr_pull_align(ndr, 8));
			NDR_CHECK(ndr_pull_uint32(ndr, NDR_SCALARS, &r->present));
			NDR_CHECK(ndr_pull_uint32(ndr, NDR_SCALARS, &r->name_conflict));
			NDR_CHECK(ndr_pull_uint32(ndr, NDR_SCALARS, &r->attributes));
			NDR_CHECK(ndr_pull_NTTIME(ndr, NDR_SCALARS, &r->fence));
			NDR_CHECK(ndr_pull_NTTIME(ndr, NDR_SCALARS, &r->clock));
			NDR_CHECK(ndr_pull_NTTIME(ndr, NDR_SCALARS, &r->create_time));
			NDR_CHECK(ndr_pull_GUID(ndr, NDR_SCALARS, &r->content_set_guid));
			size_sha1_hash_0 = 20;
			NDR_CHECK(ndr_pull_array_uint8(ndr, NDR_SCALARS, r->sha1_hash, size_sha1_hash_0));
			size_rdc_similarity_0 = 16;
			NDR_CHECK(ndr_pull_array_uint8(ndr, NDR_SCALARS, r->rdc_similarity, size_rdc_similarity_0));
			NDR_CHECK(ndr_pull_GUID(ndr, NDR_SCALARS, &r->uid_db_guid));
			NDR_CHECK(ndr_pull_hyper(ndr, NDR_SCALARS, &r->uid_version));
			NDR_CHECK(ndr_pull_GUID(ndr, NDR_SCALARS, &r->gsvn_db_guid));
			NDR_CHECK(ndr_pull_hyper(ndr, NDR_SCALARS, &r->gsvn_version));
			NDR_CHECK(ndr_pull_GUID(ndr, NDR_SCALARS, &r->parent_db_guid));
			NDR_CHECK(ndr_pull_hyper(ndr, NDR_SCALARS, &r->parent_version));
			NDR_CHECK(ndr_pull_array_length(ndr, &r->name));
			size_name_0 = 261;
			NDR_CHECK(ndr_get_array_length(ndr, (void*)&r->name, &length_name_0));
			if (length_name_0 > size_name_0) {
				return ndr_pull_error(ndr, NDR_ERR_ARRAY_SIZE, "Bad array size %u should exceed array length %u", size_name_0, length_name_0);
			}
			NDR_CHECK(ndr_check_string_terminator(ndr, length_name_0, sizeof(uint16_t)));
			NDR_CHECK(ndr_pull_charset(ndr, NDR_SCALARS, &r->name, length_name_0, sizeof(uint16_t), CH_UTF16));
			NDR_CHECK(ndr_pull_uint32(ndr, NDR_SCALARS, &r->flags));
			NDR_CHECK(ndr_pull_trailer_align(ndr, 8));
		}
		if (ndr_flags & NDR_BUFFERS) {
		}
		ndr->flags = _flags_save_STRUCT;
	}
	return NDR_ERR_SUCCESS;
}
