/* parser auto-generated by pidl */

enum ndr_err_code ndr_push_frstrans_Update(struct ndr_push *ndr, int ndr_flags, const struct frstrans_Update *r);
enum ndr_err_code ndr_pull_frstrans_Update(struct ndr_pull *ndr, int ndr_flags, struct frstrans_Update *r);
